### ISSUE TITLE
Doesn't work with Apple M1

### ISSUE THREAD

**Issue by seoplague** [wodby/elasticsearch#4]
elasticsearch | runtime: failed to create new OS thread (have 2 already; errno=22)
elasticsearch | fatal error: newosproc
elasticsearch | 
elasticsearch | runtime stack:
elasticsearch | runtime.throw(0x6249a0, 0x9)
elasticsearch | 	/home/travis/.gimme/versions/go1.6.linux.amd64/src/runtime/panic.go:530 +0x90
elasticsearch | runtime.newosproc(0xc820028000, 0xc820037fc0)
elasticsearch | 	/home/travis/.gimme/versions/go1.6.linux.amd64/src/runtime/os1_linux.go:149 +0x18c
elasticsearch | runtime.newm(0x676240, 0x0)
elasticsearch | 	/home/travis/.gimme/versions/go1.6.linux.amd64/src/runtime/proc.go:1513 +0x135
elasticsearch | runtime.main.func1()
elasticsearch | 	/home/travis/.gimme/versions/go1.6.linux.amd64/src/runtime/proc.go:125 +0x2c
elasticsearch | runtime.systemstack(0x732c00)
elasticsearch | 	/home/travis/.gimme/versions/go1.6.linux.amd64/src/runtime/asm_amd64.s:291 +0x79
elasticsearch | runtime.mstart()
elasticsearch | 	/home/travis/.gimme/versions/go1.6.linux.amd64/src/runtime/proc.go:1048
elasticsearch | 
elasticsearch | goroutine 1 [running]:
elasticsearch | runtime.systemstack_switch()
elasticsearch | 	/home/travis/.gimme/versions/go1.6.linux.amd64/src/runtime/asm_amd64.s:245 fp=0xc820022770 sp=0xc820022768
elasticsearch | runtime.main()
elasticsearch | 	/home/travis/.gimme/versions/go1.6.linux.amd64/src/runtime/proc.go:126 +0x62 fp=0xc8200227c0 sp=0xc820022770
elasticsearch | runtime.goexit()
elasticsearch | 	/home/travis/.gimme/versions/go1.6.linux.amd64/src/runtime/asm_amd64.s:1998 +0x1 fp=0xc8200227c8 sp=0xc8200227c0
elasticsearch | runtime: failed to create new OS thread (have 2 already; errno=22)
elasticsearch | fatal error: newosproc

**Comment by csandanov** [comment]
We're using adoptopenjdk/openjdk11 as our base image, unfortunately their alpine version doesn't yet support arm https://github.com/AdoptOpenJDK/openjdk-docker/issues/364

**Comment by anpel** [comment]
Is there any update on this? I can confirm I get similar output with M2.

2023-03-20 12:09:45 runtime: failed to create new OS thread (have 2 already; errno=22)
2023-03-20 12:09:45 fatal error: newosproc
2023-03-20 12:09:45 
2023-03-20 12:09:45 runtime stack:
2023-03-20 12:09:45 runtime.throw(0x6249a0, 0x9)
2023-03-20 12:09:45 /home/travis/.gimme/versions/go1.6.linux.amd64/src/runtime/panic.go:530 +0x90
2023-03-20 12:09:45 runtime.newosproc(0xc820026000, 0xc820035fc0)
2023-03-20 12:09:45 /home/travis/.gimme/versions/go1.6.linux.amd64/src/runtime/os1_linux.go:149 +0x18c
2023-03-20 12:09:45 runtime.newm(0x676240, 0x0)
2023-03-20 12:09:45 /home/travis/.gimme/versions/go1.6.linux.amd64/src/runtime/proc.go:1513 +0x135
2023-03-20 12:09:45 runtime.main.func1()
2023-03-20 12:09:45 /home/travis/.gimme/versions/go1.6.linux.amd64/src/runtime/proc.go:125 +0x2c
2023-03-20 12:09:45 runtime.systemstack(0x732c00)
2023-03-20 12:09:45 /home/travis/.gimme/versions/go1.6.linux.amd64/src/runtime/asm_amd64.s:291 +0x79
2023-03-20 12:09:45 runtime.mstart()
2023-03-20 12:09:45 /home/travis/.gimme/versions/go1.6.linux.amd64/src/runtime/proc.go:1048
2023-03-20 12:09:45 
2023-03-20 12:09:45 goroutine 1 [running]:
2023-03-20 12:09:45 runtime.systemstack_switch()
2023-03-20 12:09:45 /home/travis/.gimme/versions/go1.6.linux.amd64/src/runtime/asm_amd64.s:245 fp=0xc820020770 sp=0xc820020768
2023-03-20 12:09:45 runtime.main()
2023-03-20 12:09:45 /home/travis/.gimme/versions/go1.6.linux.amd64/src/runtime/proc.go:126 +0x62 fp=0xc8200207c0 sp=0xc820020770
2023-03-20 12:09:45 runtime.goexit()
2023-03-20 12:09:45 /home/travis/.gimme/versions/go1.6.linux.amd64/src/runtime/asm_amd64.s:1998 +0x1 fp=0xc8200207c8 sp=0xc8200207c0

**Comment by seoplague** [comment]
@anpel I used original elasticsearch image. You can overwrite settings in docker-compose.override.yml

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.14.1
    container_name: "${PROJECT_NAME}_elasticsearch"
    environment:
      - node.name=es01
      - cluster.name=es-docker-cluster
      - cluster.initial_master_nodes=es01
      - bootstrap.memory_lock=false
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ports:
      - '9200:9200'
    networks:
      - default
    labels:
      - "traefik.http.services.${PROJECT_NAME}_elasticsearch.loadbalancer.server.port=9200"
      - "traefik.http.routers.${PROJECT_NAME}_elasticsearch.rule=Host:es01.drupal.docker.localhost"
    ulimits:
      memlock:
        soft: -1
        hard: -1

**Comment by anpel** [comment]
@seoplague This worked great, thank you!
